### ISSUE TITLE
Safari zupass login not working

### ISSUE THREAD

**Issue by camilovegag** [lexicongovernance/forum-frontend#23]
### Overview

When opening the page on safari, you'll find the following:

- Get started button missing
- Popup zupass login not working
<img width="1244" alt="Screenshot 2023-12-21 at 7 55 51 AM" src="https://github.com/lexicongovernance/forum-frontend/assets/59750365/ff7f1adc-f472-4a64-a4e5-c5b2ae2e1d65">

<img width="571" alt="Screenshot 2023-12-21 at 7 56 37 AM" src="https://github.com/lexicongovernance/forum-frontend/assets/59750365/fbe42c4e-8eb5-4cfd-996f-4ec8ea9b898c">

**Comment by diegoalzate** [comment]
I think popup works now @camilovegag 

![CleanShot 2024-02-06 at 14 43 11](https://github.com/lexicongovernance/forum-frontend/assets/22416585/53ebae26-7ead-4807-bfc9-3d39cb801e8d)

but cookies does not work because of https://stackoverflow.com/questions/72224168/why-is-my-cookie-not-being-saved-on-safari-but-being-saved-on-chrome
